version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - certification-suite-network

  frontend:
    image: achintya1/certification-suite-frontend:v2
    ports:
      - "3001:3001"
    networks:
      - certification-suite-network
    env_file:  # Add this line to load environment variables from .env
      - .env 
    environment:
      - PORT=3001

  api:
    image: achintya1/certification-suite-api:v3
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - certification-suite-network
    env_file:  # Add this line to load environment variables from .env
      - .env 

volumes:
  mongodb-data:

networks:
  certification-suite-network:
